/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/paneel.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		frame_left: THREE.Mesh;
		glass: THREE.Mesh;
		frame_right: THREE.Mesh;
		frame_top: THREE.Mesh;
		frame_bottom: THREE.Mesh;
		misc_0: THREE.Mesh;
		beam: THREE.Mesh;
		misc_1: THREE.Mesh;
	};
	materials: object;
};

export function Panel(props: JSX.IntrinsicElements["group"]) {
	const { nodes } = useGLTF("/paneel.glb") as GLTFResult;
	return (
		<group scale={5} {...props} dispose={null}>
			<mesh
				geometry={nodes.frame_left.geometry}
				material={nodes.frame_left.material}
			/>
			<mesh
				geometry={nodes.glass.geometry}
				material={nodes.glass.material}
			/>
			<mesh
				geometry={nodes.frame_right.geometry}
				material={nodes.frame_right.material}
			/>
			<mesh
				geometry={nodes.frame_top.geometry}
				material={nodes.frame_top.material}
				scale={[1.003, 1, 1]}
			/>
			<mesh
				geometry={nodes.frame_bottom.geometry}
				material={nodes.frame_bottom.material}
				scale={[1.002, 1, 1]}
			/>
			<mesh
				geometry={nodes.misc_0.geometry}
				material={nodes.misc_0.material}
				scale={[1.046, 1.144, 1]}
			/>
			<mesh
				geometry={nodes.beam.geometry}
				material={nodes.beam.material}
				position={[0, 1.669, 0]}
			/>
			<mesh
				geometry={nodes.misc_1.geometry}
				material={nodes.misc_1.material}
				scale={[1.047, 1.144, 1]}
			/>
		</group>
	);
}

useGLTF.preload("/paneel.glb");
